GPU: ['0']
TRAIN:
  NUM_AUGMENT_VIEWS: 1
  PRJ_2DIM_TO_3DWD: True
  LOAD_SUB: True
  UNSUPERVISE: True
  FLIP_AUG: False
  USE_ROT_LOSS: False
NETWORK:
  TEMPORAL_LENGTH: 7
  TRANSFORM_DIM: 4
  USE_GT_TRANSFORM: False
  ROT_MODEL:
    NUM_LAYERS: 0
    NUM_CHANNELS: 300
  M_FORMER:
    GT_TRANSFORM_RES: False
TEST:
  NUM_FRAMES: [7]
  NUM_VIEWS: [4]
H36M_DATA:
  TRAIN_CAMERAS: [0, 1]
  TEST_CAMERAS: [0, 1]