#!/bin/bash
#
#
# Partition visee
#SBATCH --partition=A40-short
#
# Nombre de noeuds
#SBATCH --nodes=1
# Nombre de processus MPI par noeud
#SBATCH --ntasks-per-node=1
# Usage reserve des noeuds
#SBATCH --exclusive
#
# Temps de presence du job
#SBATCH --time=1-00:00:00
#
# Adresse mel de l’utilisateur
  #SBATCH --mail-user=kevin.riou@etu.univ-nantes.fr
# Envoi des mails
#SBATCH --mail-type=fail,abort,end
#
# Nom du fichier de log de Slurm pour le job
#SBATCH -o out_cs_GT_signal.out
#SBATCH -e err__cs_GT_signal.err


module load python/3.9.4

source ./bin/activate
python run_h36m_relative_pose_cam_s_P_GT.py --cfg ./cfg/submit/u_P_R_cs_GT_signal.yaml
