#!/bin/bash
#
#
# Partition visee
#SBATCH --partition=AMD-short
#SBATCH --gpus-per-node=1
#
# Nombre de noeuds
#SBATCH --nodes=1
# Nombre de processus MPI par noeud
#SBATCH --ntasks-per-node=1
# Usage reserve des noeuds
#SBATCH --exclusive
#
# Temps de presence du job
#SBATCH --time=1-00:00:00
#
# Adresse mel de l’utilisateur
  #SBATCH --mail-user=kevin.riou@etu.univ-nantes.fr
# Envoi des mails
#SBATCH --mail-type=fail,abort,end
#
# Nom du fichier de log de Slurm pour le job
#SBATCH -o out_sup_t41_2.out
#SBATCH -e err_sup_t41_2.err


module load python/3.9.4

source ../pose3d-up2date/bin/activate
python run_h36m_waypoints.py --cfg ./cfg/submit/config_waypoints_task_41.yaml --resume_checkpoint ./checkpoint/submit/config_waypoints_task_41_2023-02-15-19-23/model.bin
